### ISSUE TITLE
Error: Evaluation Error: Resource type not found: Deferred (file: /etc/puppet/code/modules/concat/manifests/fragment.pp, line: 21, column: 47)

### ISSUE THREAD

**Issue by albsol** [smoeding/puppet-sendmail#29]
Hello,
I'm using Vagrant created virtual severs to try your puppet-sendmail module. 
I've tried with Debian 11, Ubuntu (18.04, 20.04, 22,04), but sendmail configuration is never installed, it always returns this error message:
        Error: Evaluation Error: Resource type not found: Deferred (file: /etc/puppet/code/modules/concat/manifests/fragment.pp, line: 21, column: 47) 

The steps I follow:
```
# apt-get update
# apt install puppet
# puppet module install stm-sendmail --version 3.3.0
# echo "class { 'sendmail': }" > /vagrant/sendmail.install.config.pp

# puppet apply /vagrant/sendmail.install.config.pp
Warning: /etc/puppet/hiera.yaml: Use of 'hiera.yaml' version 3 is deprecated. It should be converted to version 5
   (file: /etc/puppet/hiera.yaml)
Error: Evaluation Error: Resource type not found: Deferred (file: /etc/puppet/code/modules/concat/manifests/fragment.pp, line: 21, column: 47) on node localdev.example.com
``` 

Any idea?, perhaps is some dependency missing?

**Comment by smoeding** [comment]
Again this seems to be a problem with the Concat module caused by using a legacy Puppet release. Puppet. 6 has been EOL since February...

The Error "undefined method `filter_map'" is also triggered inside the Concat module. The latest Concat module is no longer compatible with Puppet 6 (Puppet Agent 6.x is bundled with Ruby 2.5 and the referenced method is only available in Ruby 2.7 an later).

You should use either Puppet 7 or make sure you only use module releases that are compatible with Puppet 6.
